# carsizeshtml.py - Create an HTML table from a list of car sizes.
# Generated by Github Copilot via MRR on 2025-01-11.
import json

# This table was generated by ChatGPT in response to my queries. 
data = [
    {
        "model": "Porsche Taycan",
        "length_inches": 195.4
    },
    {
        "model": "Porsche Macan EV",
        "length_inches": 188.3
    },
    {
        "model": "Ford Mustang Mach-E",
        "length_inches": 186.0
    },
    {
        "model": "2023 Kia Sportage PHEV",
        "length_inches": 183.5
    },
    {
        "model": "Audi Q4 e-tron",
        "length_inches": 180.7
    },
    {
        "model": "Genesis GV60",
        "length_inches": 177.8
    },
    {
        "model": "2007 Toyota Prius",
        "length_inches": 175.0
    },
    {
        "model": "Volvo C40 Recharge",
        "length_inches": 174.8
    }
]

# Create the HTML table
html = '<table border="1">\n'
html += '  <tr><th>Model</th><th>Length (inches)</th></tr>\n'

# Process each item in the JSON data
for item in data:
    model = item["model"]
    length_inches = item["length_inches"]
    html += f'  <tr><td>{model}</td><td>{length_inches}</td></tr>\n'

html += '</table>'

# Print the HTML table
print(html)
